name: Generate README

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: ruby/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - run: npm ci
      - env:
          DEXCOM_EMAIL: ${{ secrets.DEXCOM_EMAIL }}
          DEXCOM_PASSWORD: ${{ secrets.DEXCOM_PASSWORD }}
        run: npm run once
